### ISSUE TITLE
Switch terminology from "OEM Repo" to "Image Repo"

### ISSUE THREAD

**Issue by awwad** [uptane/obsolete-reference-implementation#10]
_From @awwad on December 1, 2016 21:55_

It seems that there is a consensus that "Supplier Repository" should be the term to refer to the main repository of metadata and targets. There may be a few mentions in the reference implementation that should be changed, along with the many references in the demonstration code.

_Copied from original issue: awwad/uptane#17_

**Comment by trishankkarthik** [comment]
Following consensus from the last workshop, it's "image repository" now.

**Comment by vladimir-v-diaz** [comment]
Should we close this issue since it was fixed in https://github.com/awwad/uptane/pull/39?

**Comment by awwad** [comment]
Yes, true. Thanks. (:
