### ISSUE TITLE
cffi 1.7.0 not compatible with cryptography 1.7.2

### ISSUE THREAD

**Issue by JosiahOne** [uptane/obsolete-reference-implementation#139]
### Problem Summary
On a Raspberry Pi, `cffi==1.7.0` is not compatible with `cryptography==1.7.2`, and `cryptography` won't install. I'm not sure why this doesn't happen on other platforms (Windows + cygwin seems to work fine). 

I've attached a portion of the log showing the failure: [pipInstallError.txt](https://github.com/uptane/uptane/files/1326706/pipInstallError.txt)

### Expected Behavior
`pip install -r dev-requirements.txt` should successfully install uptane and its dependencies.

### Actual Behavior
`pip install -r dev-requirements.txt` fails (see log above)

### Solution

This can be fixed by using `cffi==1.11.0` instead. I made that change and ran `tox ` and there were no regressions. I wonder if Uptane really needs to force `cffi==1.11.0`? cryptography will install the correct version automatically.

**Comment by JosiahOne** [comment]
Obviously this isn't really Uptane's fault. It seems to be the fault of either cryptography or cffi, but Uptane should work around this since a Pi is an excellent platform to test on.

**Comment by JosiahOne** [comment]
Looks like this happens on Ubuntu as well.

**Comment by awwad** [comment]
Sorry for not updating the issue: I couldn't seem to reproduce this. I have several Pis here that are running cffi 1.7.0 and cryptography 1.7.2 and running Uptane. You might be having an environment setup issue? Still, it shouldn't hurt for me to update the dependencies to point to more recent versions of both libraries. I'll try that out when I have some cycles.

**Comment by JosiahOne** [comment]
BTW, I just tried setting up a new uptane development environment on a (pretty new) Debian VM and hit the same issue. The exact setup script that reproduces this problem looks like:
```
  1 sudo apt-get install build-essential libssl-dev libffi-dev python-dev python3-dev
  2                                                                                 
  3 git clone https://github.com/uptane/uptane                                      
  4 cd uptane                                                                       
  5                                                                                 
  6 python3 -m venv env                                                             
  7 source env/bin/activate                                                         
  8                                                                                 
  9 python3 -m pip install --upgrade pip                                            
 10 python3 -m pip install -r dev-requirements.txt                                  
 11 python3 tests/runtests.py            
```                                           

Line 10 fails for me with the same error as above.

**Comment by awwad** [comment]
Thanks for reporting. I'll take a look again.

**Comment by awwad** [comment]
Sorry - closing was automatic. Is this resolved for you with the dependency updates?

**Comment by JosiahOne** [comment]
Yep, works great now! I'll close....
