### ISSUE TITLE
Not executing the command in second window

### ISSUE THREAD

**Issue by koruthu** [uptane/obsolete-reference-implementation#168]
While executing the commands("ds.clean-slate()") that you written in demo section of window 2, I am getting the following error:
The given ECU is not in this Primary's list of known Secondary ECUs. Register the ECU with this Primary first.">
can you tell me the possible solution. As well which is stable release, and how to build your package effectively?

**Comment by awwad** [comment]
It looks like you're running the Secondary before running the Primary.  The second window in the demo is the Primary.

<img width="1132" alt="screen shot 2019-03-01 at 09 55 03 4" src="https://user-images.githubusercontent.com/13263928/53646010-2e8e6680-3c08-11e9-8636-368898063b34.png">

**Comment by koruthu** [comment]
Hi,
Thanks for your reply @awwad 

And we were able to build and run the demo, but I have few questions: 
> How to update primary itself?
> How to run server and client in two different system?

**Comment by awwad** [comment]
See #174.
