### ISSUE TITLE
Demo contains invalid code

### ISSUE THREAD

**Issue by heartsucker** [uptane/obsolete-reference-implementation#22]
From the demo in the `README`

```
>>> new_target_fname = dd.demo.DIRECTOR_REPO_TARGETS_DIR + '/file5.txt'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'demo' has no attribute 'DIRECTOR_REPO_TARGETS_DIR'
```

**Comment by awwad** [comment]
I'll take a look, thanks. There have been some changes, and it's possible the demo instructions are out of sync.

**Comment by heartsucker** [comment]
Yeah, it actually goes a wee bit further too.

```
>>> dd.add_target_to_director(new_target_fname, ecu_serial='123')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add_target_to_director() missing 2 required positional arguments: 'filepath_in_repo' and 'vin'
>>> dd.add_target_to_director(new_target_fname, filepath_in_repo='file5.txt', vin='123', ecu_serial='123')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/heartsucker/code/misc/uptane/demo/demo_director.py", line 232, in add_target_to_director
    raise uptane.UnknownVehicle('The VIN provided, ' + repr(vin) + ' is not '
uptane.UnknownVehicle: The VIN provided, '123' is not that of a vehicle known to this Director.
```

There's no mention of how to register a VIN with the director.

**Comment by awwad** [comment]
I'm fixing the instructions now. Normally, in the demo, VINs and ECU Serials are registered with the Director when they're "created" (by starting the demo Primary and/or demo Secondary code). You can, however, register ECUs and vehicles directly from the demo Director:

[dd.director_service_instance.register_ecu_serial(ecu_serial, ecu_key, vin, is_primary)](https://github.com/uptane/uptane/blob/develop/uptane/services/director.py#L118-L138) will register an ECU as a Primary or Secondary ECU to the given VIN. (If the vehicle isn't already registered, it should be registered as a result of this.)

It might be a bit of a hassle to figure out the formats for that internal call. It's probably easier to just run the demo Primary in a separate window.

**Comment by awwad** [comment]
Instructions fixed. Thanks for tinkering!

**Comment by awwad** [comment]
I'm going to close this, but if I've missed something somewhere, please let me know.
