### ISSUE TITLE
Demo: Automatically kill http server process

### ISSUE THREAD

**Issue by awwad** [uptane/obsolete-reference-implementation#29]
Starting the demo Director (demo_director) or demo Image Repository (demo_oem_repo) Popens an http simple server process. Currently, users are instructed to kill this background process before exiting by running do.kill_server() or dd.kill_server() (respectively) before running exit().

Automate this so that when the Python shell exits, these are killed without user intervention.

**Comment by baloian** [comment]
please have a look PR #39
