### ISSUE TITLE
Add function to make key updates easy

### ISSUE THREAD

**Issue by awwad** [uptane/obsolete-reference-implementation#36]
### Background
Revoking, adding, etc. a key in Uptane is essentially the same as it is in TUF, using the TUF repository objects that exist in the reference implementation.

### Task
There should, however, be code in the reference implementation (or at least the demo) that does this in a clear, readable way, so as to illustrate this to implementers.

### Details
Example of how this is done now:
Suppose I'm writing a script for the demo Director that revokes an old signing key for a role and adds a new one. I would do something along these lines:
vehicle_repositories[vin]

If I wanted to update the timestamp key on the Director repo right now, I would make calls like this for each vehicle repository:
```python
# fetch signing key id as current_key
director_service_instance.vehicle_repositories[vin].timestamp.unload_signing_key(current_key)
# make similar call to remove verification key if necessary
director_service_instance.vehicle_repositories[vin].timestamp.add_verification_key(new_key)
director_service_instance.vehicle_repositories[vin].timestamp.load_signing_key(new_key)
```
and then perform a repository write for each repository.

This is especially burdensome for the Director, and should be captured in functions in director.py called something like `add_key_for_role(role, new_key)` and `revoke_key_for_role(role, old_key)`. It's worth considering threshold modifications as you write these functions, so that they don't break in case someone needs to update the thresholds. (It's okay to still require that to be done directly, manually, but your code should ideally not break if that happens.)

In the longer term, it will probably make sense to capture this functionality at a lower level in some functions in uptane/common.py that might look like this:
- `common.py:add_key_to_role(repo_object, role, key)`
- `common.py:remove_key_from_role(repo_object, role, key_id)`

which could in turn be called by the functions discussed above (`director.py:add_key_for_role` would make several calls to `common.py:add_key_for_role`, for example).

**Comment by vladimir-v-diaz** [comment]
This issue was implemented in https://github.com/uptane/uptane/issues/45.  Should we close it and perhaps open a new issue for the long term goal (where functions are added to common.py)?

**Comment by awwad** [comment]
Yes, I think we should close this. I'm not sure we should implement the common.py functions now. I guess we can make an issue to ask that question, yeah.
